### ISSUE TITLE
Cannot read properties of undefined (reading 'states')

### ISSUE THREAD

**Issue by ABUAIJUTIE** [dimagoltsman/refreshable-picture-card#25]
Get this ERROR:

> Cannot read properties of undefined (reading 'states')

with these codes:

```
type: custom:refreshable-picture-card
title: TEST
refresh_interval: 30
noMargin: true
entity: media_player.tv
attribute: entity_picture
```

**Comment by lemeshovich** [comment]
same error for me
```
type: custom:refreshable-picture-card
refresh_interval: 3
entity: camera.room_cam
noMargin: true
attribute: entity_picture
```

**Comment by seanblanchfield** [comment]
I am also experiencing this since updating from 0.1.12 to 0.2.1. The error occurs on line [119 of `refreshable-picture-card.js`](https://github.com/dimagoltsman/refreshable-picture-card/blob/21795c37e12a01f3d79b11f7261ca3446a7029be/dist/refreshable-picture-card.js#L119), where it attempts to access the `this.hass` object.  This is being called from [`_getTimestampedUrl()`](https://github.com/dimagoltsman/refreshable-picture-card/blob/21795c37e12a01f3d79b11f7261ca3446a7029be/dist/refreshable-picture-card.js#L124), which is called from the [`setConfig()`](https://github.com/dimagoltsman/refreshable-picture-card/blob/21795c37e12a01f3d79b11f7261ca3446a7029be/dist/refreshable-picture-card.js#L54) method.  The problem is that the `hass` property has not been set by Home Assistant at the time that `setConfig()` is run.  It appears `setConfig()` crashing is fatal, because `render()`  is never subsequently invoked and the `hass` property is never set.

Anyone desperate for a fix can work around this issue by specifying a URL instead of an entity, combined with a template expression that fetches a correct and current URL.  When no `entity` is specified, the [offending function returns early](https://github.com/dimagoltsman/refreshable-picture-card/blob/21795c37e12a01f3d79b11f7261ca3446a7029be/dist/refreshable-picture-card.js#L116) and this exception is avoided. I specify the URL as follows:
``` yaml
url: {{ state_attr("camera.driveway_sub", "entity_picture") }}
```

I suggest that the long-term solution is to move the following line from the `setConfig()` function to the `render()` function. This avoids it running before the `this.hass` property is set, but still runs it more or less immediately for instant rendering of the picture.
``` javascript
this.pictureUrl = this._getTimestampedUrl();
```
I have tried this fix locally and can confirm that it works.

**Comment by LeonB87** [comment]
I tried your fix, But I cannot get it to work on my end.

There's either no picture, or the **missed comma between flow collection entries (4:63)** error
I validated the URL returned is correct.

```yaml
type: custom:refreshable-picture-card
title: test
refresh_interval: 15
url: {{state_attr("media_player.spotify_leon","entity_picture")}}
````

Hopefully @dimagoltsman can take a look at your fix once he has the opportunity
