### ISSUE TITLE
Refresh Interval in GUI says NaN

### ISSUE THREAD

**Issue by ulanking** [dimagoltsman/refreshable-picture-card#31]
In the GUI, when you try to drag the "Refresh Interval" slider, it reports the error "NaN"

Also the photo isn't refreshing.

HACS version 1.32.1
Refreshable Picture Card version 0.2.0

**Comment by ulanking** [comment]
Picture: 
![202417_NAN](https://user-images.githubusercontent.com/177106/232638211-82aebcae-2e90-4fc2-9e87-2cadde2d6c45.jpg)

**Comment by ulanking** [comment]
Updated to version 0.2.1 - same issue. when trying to set the refresh interval.

**Comment by sanzoghenzo** [comment]
Hi, 
The problem with the slider is that, in my PR that added the configuration GUI, I didn't set up a maximum value, since there shouldn't be a limit.
As you may have already found out, you can still set the number of seconds in the input box.

The quick fix to this issue is simply remove the slider by adding `"mode": "box"` to the [selector config](https://github.com/dimagoltsman/refreshable-picture-card/blob/a173411bbd3ebd0621c7482881e306815cac9e4d/dist/refreshable-picture-card-editor.js#LL31C14-L31C14)

Another way could be moving to a `duration` selector, but it involves handling the different output, since it would not be an integer of seconds anymore, but an object with `hours`, `minutes` and `seconds` properties.
Obviously this will be a breaking change.

@dimagoltsman let me know what you think about that, and if you want me to to the PR for this!

**Comment by dimagoltsman** [comment]
@sanzoghenzo  PRs are always welcome :)
